### ISSUE TITLE
Please support jessie

### ISSUE THREAD

**Issue by bjvrielink** [camptocamp/puppet-dhcp#10]
When trying to use this module, I am greeted by:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: No matching value for selector param 'jessie' at /etc/puppet/environments/production/modules/dhcp/manifests/params.pp:14 on node bob.dontpanic.nl

This is caused by not having either a 'jessie' or 'default' option in the params.pp file for various configuration parameters.

**Comment by mcanevet** [comment]
@bjvrielink PR welcome
