### ISSUE TITLE
shared-network and includes

### ISSUE THREAD

**Issue by 69bossmustang** [camptocamp/puppet-dhcp#24]
It seems if you use shared networking the includes don't actually work. The best I can figure is that dhcpd doesn't allow include directive within brackets?

`
shared-network net09-shared {
    include "/etc/dhcp/subnets/10.0.10.0.conf";
    include "/etc/dhcp/subnets/10.0.21.0.conf";
    include "/etc/dhcp/subnets/10.0.32.0.conf";
}
`
The above would not work, if I copy/pasted the included file contents and placed it within the shared-network block it worked. My first thought was it was file permissions but I ran various settings on those and it did not function. My last test was to copy the data from the included directives into a single file and added the shared-network to that file then included that file it worked.

So, best I can tell is dhcpd doesn't like include's in {}'s. So the method the module uses will need to change.

**Comment by raphink** [comment]
OK. I'm open to suggestions/PR to fix this.

**Comment by 69bossmustang** [comment]
This turned out to be an issue with foreman ALSO parsing the data and making me think it was related to dhcpd which infact dhcpd worked fine. Updated parsing in foreman and it deals with it properly. Apologies for the false report.

**Comment by raphink** [comment]
Thanks for clarifying it. I'll close then.
